name: 'Setup Project'
description: 'Checkout code, setup Node.js, install dependencies, and optionally generate Prisma client'

inputs:
  generate-prisma:
    description: 'Whether to generate Prisma client'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Generate Prisma Client
      if: inputs.generate-prisma == 'true'
      run: npm run db:generate
      shell: bash
