name: Chromatic

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Chromatic needs full git history for baseline comparison

      - uses: ./.github/actions/setup

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # Auto-accept changes on main branch, manual review on PRs
          autoAcceptChanges: ${{ github.ref == 'refs/heads/main' }}
          # Exit with error if there are visual changes (optional, can be removed)
          exitOnceUploaded: false
