name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup

      - name: Check code formatting
        run: npm run format:check

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup

      - name: Run ESLint
        run: npm run lint

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          generate-prisma: "true"

      - name: Run TypeScript type check
        run: npm run type-check

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          generate-prisma: "true"

      - name: Run tests
        run: npm run test:run

  build:
    name: Build Application
    needs: [format, lint, type-check, test]
    runs-on: ubuntu-latest
    env:
      # Dummy values for build-time environment variables
      DATABASE_URL: postgresql://user:password@localhost:5432/db
      DIRECT_DATABASE_URL: postgresql://user:password@localhost:5432/db
      NEXTAUTH_SECRET: dummy-secret-for-ci-build-only
      NEXTAUTH_URL: http://localhost:3000
      GOOGLE_CLIENT_ID: dummy-client-id
      GOOGLE_CLIENT_SECRET: dummy-client-secret
      SKIP_ENV_VALIDATION: true

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
        with:
          generate-prisma: "true"

      - name: Build application
        run: npm run build
