name: Lint, Type Check, and Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-and-build:
    name: Run Quality Checks
    runs-on: ubuntu-latest

    env:
      # Dummy values for build-time environment variables
      DATABASE_URL: postgresql://user:password@localhost:5432/db
      NEXTAUTH_SECRET: dummy-secret-for-ci-build-only
      NEXTAUTH_URL: http://localhost:3000
      GOOGLE_CLIENT_ID: dummy-client-id
      GOOGLE_CLIENT_SECRET: dummy-client-secret
      SKIP_ENV_VALIDATION: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript type check
        run: npm run type-check

      - name: Build application
        run: npm run build
